package info.fantasysoul.dal.common;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

import info.fantasysoul.dal.modal.UserInfo;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("user_info", "user_id", UserInfo.class);
	}
}

